#!/bin/bash

export HOME=`dirname $0`

export LIB_HOME="$HOME/lib"

export JUNIT_HOME="${LIB_HOME}/junit-4.8.2"

export COBERTURA_HOME="${LIB_HOME}/cobertura-1.9.4.1"

export CLASSPATH="${JUNIT_HOME}/junit.jar:${COBERTURA_HOME}/cobertura.jar:${COBERTURA_HOME}/lib/asm-3.0.jar:${COBERTURA_HOME}/lib/asm-tree-3.0.jar:${COBERTURA_HOME}/lib/jakarta-oro-2.0.8.jar:${COBERTURA_HOME}/lib/log4j-1.2.9.jar"

export CLASSPATH_OVERRIDE=1

ant -buildfile "$HOME/build.xml" $@
